### ISSUE TITLE
excluded_repositories always generates a diff

### ISSUE THREAD

**Issue by blabu23** [jfrog/terraform-provider-artifactory#1143]
Configuring an artifactory_backup resource want to update the parameter excluded_repositories every time, even after a successful apply.

```
resource "artifactory_backup" "backup-weekly" {
  key                       = "backup-weekly"
  enabled                   = true
  cron_exp                  = "0 0 12 * * SAT *"
  retention_period_hours    = 1000
  excluded_repositories     = []
  create_archive            = false
  exclude_new_repositories  = true
  send_mail_on_error        = true
  verify_disk_space         = true
  export_mission_control    = true
}
```

```
t plan:
...
  # artifactory_backup.backups["backup-weekly"] will be updated in-place
  ~ resource "artifactory_backup" "backup-weekly" {
      + excluded_repositories    = []
        # (9 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

```
t apply:
...
artifactory_backup.backup-weekly: Modifications complete after 0s
```

```
t plan (all subsequent runs):
...
  # artifactory_backup.backups["backup-weekly"] will be updated in-place
  ~ resource "artifactory_backup" "backup-weekly" {
      + excluded_repositories    = []
        # (9 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

- JFrog Platform EnterpriseX license 7.98.9 rev 79809900
- Terraform version 1.5.5
- Provider version 12.5.1

**Expected behavior**
After a successful apply it should not display the parameter as a diff again...

**Comment by alexhung** [comment]
@blabu23 The reason this issue arises is because Artifactory API doesn't distinguish between a value not being set or empty. So for `excluded_repositories`, there's no functional difference if it is not set in the API or set to `[]`. However, Terraform **cares** so if you omit this attribute in your configuration the state drift will not occur.

I'm going to add validation to this attribute to ensure it must have at least 1 item if it is set in the configuration.
