### ISSUE TITLE
Unable to import/manage users due to Error: no usersname supplied

### ISSUE THREAD

**Issue by spuder** [jfrog/terraform-provider-artifactory#132]
Attempting to re-import artifactory users into terraform (after we lost all data and had to restore from backup)

Version=2.3.6

```bash
Error: no usersname supplied
```

```terraform
resource "artifactory_user" "npm-write" {
  name              = "npm-write"
  email             = "artifactory@example.com"
  groups            = ["npm-write", "readers"]
  disable_ui_access = true
}
```

```bash
terraform import artifactory_user.npm-write npm-write
artifactory_user.npm-write: Importing from ID "npm-write"...
artifactory_user.npm-write: Import prepared!
  Prepared artifactory_user for import
artifactory_user.npm-write: Refreshing state... [id=npm-write]

Error: no usersname supplied

```

**Comment by spuder** [comment]
I'm not seeing any parameter named `usersname` in the documentation https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_user

**Comment by chb0github** [comment]
Ok, that's a typo in the error output, not an actual parameter. However, it is saying that there is no "name" being supplied in the resource. But, I see that you do, in fact, have it assigned. 

I will try to reproduce it today by:
1. Creating that user in artifactory
2. running this import.

**Comment by spuder** [comment]
Looks like this was fixed in 2.3.10
https://github.com/jfrog/terraform-provider-artifactory/commit/a42a045cc0782c4a858f398a941e20cfa22a56d3

However we are seeing the same error after upgrading

```
tf import artifactory_user.npm-write npm-write
artifactory_user.npm-write: Importing from ID "npm-write"...
artifactory_user.npm-write: Import prepared!
  Prepared artifactory_user for import
artifactory_user.npm-write: Refreshing state... [id=npm-write]

Error: 'name' not supplied
```

```
resource "artifactory_user" "npm-write" {
  name              = "npm-write"
  email             = "artifactory@example.com"
  groups            = ["npm-write", "readers"]
  disable_ui_access = true
}
```

**Comment by wc-s** [comment]
`2.3.10` only fixed the error message, not the actual issue.

I'm actually running into the same issue as well. I have a PR that attempts to fix this: https://github.com/jfrog/terraform-provider-artifactory/pull/145/files, review would be very welcome, thanks.

(I'm quite sure of the root cause, but I'm not very familiar with terraform provider development, so I'm not sure whether the changes would inadvertently break anything else, though I feel that it shouldn't.)

(I have tested the code change on a live artifactory instance, but have still not set up the terraform provider acceptance tests... - the PR description has more details.)

**Comment by chb0github** [comment]
@wc-s 

I create this user locally. Then tried with existing code. Failed as described. Applied your changes: Works. Now I just need that test in your PR to merge

**Comment by wc-s** [comment]
Fixed the test. Explanation in the PR comments.
