### ISSUE TITLE
Endpoints prepend /artifactory to the path

### ISSUE THREAD

**Issue by javierlga** [jfrog/terraform-provider-artifactory#146]
**Describe the bug**
Artifactory endpoints are hardcoded to prepend `/artifactory` to the path.

- Terraform snippet:
```
terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "2.3.10"
    }
  }
}

data "artifactory_file" "generic_file" {
  repository  = var.repository_name
  path        = var.file_path
  output_path = var.file_output_path
}
```
- Artifactory version: 6.19.0
- Terraform version: 0.13.5

**Expected behavior**
Some URL endpoints (didn't check all of them) on provider version **2.3.10** are hardcoded to a specific path, for example: 

https://github.com/jfrog/terraform-provider-artifactory/blob/c82d69838f08cdd119eb07496aa8a8732abae733/pkg/artifactory/datasource_artifactory_file.go#L113

In our scenario, the correct path starts only with `api/storage/repository/path` causing 404 errors when trying to use version **2.3.10**. 

Older provider versions such as **2.2.0** didn't have this behavior, sticking to this version is a workaround for now, but would like to use newer provider versions in the future.

**Comment by chb0github** [comment]
Well, it isn't just the hard coding. In the provider when the connection is created, the extra `/artifactory` or anthing else you might have added gets thrown away. And, it has to since this TF provider also has xray support which would be `/xray` 

Someone else had months ago had made a similar complaint, but we simply can't allow people custom infra and still make it work. `/artifactory` and `/xray` are the default paths for those services on our platform. If you've remapped them we won't be able to help you

**Comment by javierlga** [comment]
> Well, it isn't just the hard coding. In the provider when the connection is created, the extra `/artifactory` or anthing else you might have added gets thrown away. And, it has to since this TF provider also has xray support which would be `/xray`

Well, I don't understand why this behavior changed in newer versions, is there a particular reason? 
 
> Someone else had months ago had made a similar complaint, but we simply can't allow people custom infra and still make it work. `/artifactory` and `/xray` are the default paths for those services on our platform. If you've remapped them we won't be able to help you

Wouldn't it be easier to take the URL provided in the provider block as the base? For example:

```
provider "artifactory" {
  url     = "https://artifactory.example.com/api" 
  api_key = var.api_key
}
```
That would make that all API calls use `https://artifactory.example.com/api`. This just adds more flexibility to the code than just forcing the customers to use the default paths, so then I don't know why custom installations are available.

**Comment by chb0github** [comment]
The solution gets more complicated - even your example is incomplete. You'd need something like:
```tcl
provider "artifactory" {
  rt_url     = "https://artifactory.example.com/artifactory"
  xr_url     = "https://artifactory.example.com/xray"
  prjk_url = "https://artifactory.example.com/api/v1/projects" 
  api_key = var.api_key
}
```

Projects is next on the list and the base URI is entirely different. You're only the 2nd person in almost a year to bring this up, so I don't consider it a burning need and it adds a bunch of complexity to the TF provider that only arises because the customer made a personalised decision about their infra. Honestly, it's an infra problem with an easy infra fix: use a local proxy to rewrite. 

That, this change was actually made [long, long ago. ](1ab6cf9e3a0491b33dd4ed71cc708b72ddbca8c0). In your case your making the assumption that it's only RT being serviced. You could have to give an endpoint for every service.

I'll leave this issue open for a while, but it definitely isn't a bug an it's been a change in place for a long time. I don't considered an enumerated mapping of `service => endpoint` a worthwhile endeavour without may many more upvotes.
