### ISSUE TITLE
[Question/Request] Level of support/reliability for this provider?

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#167]
I've _just_ started looking at this Terraform Provider over the past week, and I don't have any context about how much "love" it receives as an "official" product (vs being treated as a side-project by the company), but it would be fantastic if this provider were more reliable than the API endpoints.

Here's a concrete example: Creating access tokens for users.

1. There is the [`POST /api/security/token`](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateToken) endpoint, which is perfectly capable of generating a new token for a user, and you can specify the group (which has permissions associated with it).

1. However, this endpoint is marked (in the documentation) as _deprecated_ in favor of `POST /access/api/v1/tokens`.

1. So we go to use the new (non-deprecated) [endpoint](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AccessTokens) (like the documentation suggests), and try to create a user with the expectation that this user's token should have the same access as the user has in the UI. This results in stepping on a landmine.

    1. Firstly, neither Basic Auth **NOR** API Keys work for this endpoint. I knew that [Basic Auth was deprecated](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-Authentication), but had no idea that API Keys were too (especially since the [authentication docs](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-Authentication) specifically say that you can use an API Key). You MUST use Access Tokens (the thing I'm trying to create).

    1. `scope` is a mess. The documentation for how to use `applied-permissions/groups` is incomplete and unusable which is frustrating enough, but then I find out from support that the **new** endpoint doesn’t have parity yet, even though the **old** endpoint is marked as deprecated already. In short, everything about it is broken from the user perspective.

    1. How do you refresh a token? The documentation doesn't say. OH! You have to pass a _different_ `grant_type` that _isn't f***ing documented_. (It’s `grant_type=refresh_token`, BTW.)

    1. Also, `expires` works differently from how it used to. But you don't know that until you try to use it because, again, the docs are wrong/unclear/incomplete.

----

So here's what I would like to do:

1. Use the Terraform Provider for Artifactory → [`artifactory_access_token`](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_access_token) resource.

1. It does the right thing. (!)

1. [Nice-to-have] The [Provider docs](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs) are _better_, _clearer_, and _more detailed_ than what's in the JFrog wiki.

1. The _provider_ is responsible for making the right calls to the right endpoints. I don't have to ever think about which parts of the API are deprecated  or partially implemented or not.

1. A break in the upstream API shouldn't necessarily break the Provider interface. The _Provider_ is responsible for _massaging_ the Terraform inputs to match the API inputs. If it can't be _massaged_, then the Provider receives a major version bump where the end-user knows that they need to update their code.

It looks like this _may_ already be the case. In which case, **awesome!** But it's not clear enough that I could "take it to the bank and cash it."

Semantic versioning is a _partial_ software contract, but not a complete software contract by itself. There's some nuance in the definition of semantic versioning as it pertains to software which communicates with APIs, because APIs don't necessarily follow the rules of semver — especially in the minor versioning.

Would it be possible to update the language in the README to explain _this part_ of the software contract? What the intentions are for how semver is applied? What level of support it receives from JFrog? Does this Terraform Provider fall under the umbrella of my über-expensive enterprise support contract? For example:

1. With my API endpoint deprecation example above, is that major or minor?

1. What about changes to things like required TLS versions? (This is a fairly contrived example for languages like Go, but less contrived for software written in Ruby or PHP where the underlying OS has more to do with support than the language runtime itself. But these are things that many software vendors fail to think about.)

1. The README currently says “We increment the minor version with any backwards-compatible **changes** to functionality” (emphasis added), which is subtly different from “We increment the minor version with any backwards-compatible **additions** to functionality”. The language is ambiguous enough that this could also include _removals_ of things deemed unimportant, which is a violation of strict semver, but I've seen bigger companies fudge this before (e.g., AWS SDK for Go).

1. Can I file a ticket at https://support.jfrog.com if I need an expedited response to an issue in this Terraform Provider?

----

None of this stuff is pressing, of course, but it all falls under the category of "undefined" (or, at least, I couldn't find it). I'd be interested in understanding the bounds we're working with, so that I can set my expectations accordingly. Does JFrog consider this a nice-to-have (if it works, it works)? Or is this stable/supported enough that I can work with my team to invest in the use of this Provider to ensure that this critical, tier-1 service has as little disruption as humanly possible?

**Comment by chb0github** [comment]
Ok, you forced me to read this a few times; it's 2/3 legitimate gripe, 1/3 asks

I am currently the only engineer supporting and advocating for this provider. It is a fork from the atlassian provider and the most recent major version release ditched all non-jfrog dependencies. At this point it's an entirely independent implementation. In the process, some things I intentionally decided to no longer support for any number of reasons. I tried to document what I found along the way while ditching atlassian. 

You have a lot of questions here, and I am happy to answer them; my only ask is that you make it 1-question/ask 1 issue. This makes it easier to answer and for others to find.

## In response to the question title ##

### Level of support: ### 
There is currently 1 engineer dedicated full time to supporting this provider 👋 , but I am dedicated full time.

### Reliability: ### 
Up until a few months ago, no one was dedicated to supporting this provider and priorities were different. I am a pretty seasoned developer and my goals are, as follows:
1. All tests pass, and missing tests are implemented
2. bugs on github are addressed quickly and, when practical, given priority over features
3. Feature requests are worked on in a combination of: `time outstanding`, `ease of implementation`, `how much the change is requested` and `my capacity to juggle them`. 

For example: I am just now getting to feature requests from last feb, but they are happening now and picking up speed because the tests actually pass. So, new code can be confidently rolled out. In addition, I have done some refactoring to remove redundant code. Meaning changes are much smaller. 

For all the rest of your requests and questions, _please just create individual issues and I can answer_
