### ISSUE TITLE
Intermittent issue of data "artifactory_file" resource not being refreshed

### ISSUE THREAD

**Issue by nbshetty** [jfrog/terraform-provider-artifactory#176]
What we've noticed sometimes as part of a build the data "artifactory_file" does not get refreshed i.e. the artifactory file does not get downloaded. Which breaks our downstream resource creation. Issue seems to persist for sometimes and then automatically resolves itself. We've not noticed any errors or warning in the logs.

Basically what we are looking for is pointers on whether anyone else have reported such issues before or there are any logs that we can switch on that will help in analysing this issue.

```hcl
terraform {
  required_version = ">= 1.0.6"

  backend "s3" {
    encrypt = "true"
  }

  required_providers {
    aws        = {}   
    artifactory = {
      source = "registry.terraform.io/jfrog/artifactory"
    }
  }
}

provider "aws" {
  region = var.region
}

provider "artifactory" {  
}


data "artifactory_file" "zip" {
  repository      = var.rules_refresh_lambda_package.repo
  path            = "${var.rules_refresh_lambda_package.path}/${var.rules_refresh_lambda_package.package}"
  output_path     = "${path.root}/${var.rules_refresh_lambda_package.package}"
  force_overwrite = true  
}
```

 Artifactory Version "version": "7.25.7"  "revision": "72507900",
 Terraform Version 1.0.6

**Expected behavior**
zip file to be downloaded to the terraform root

**Comment by chb0github** [comment]
I can't work with this sample; there are references to things outside this tf script everywhere.  You also don't have the provider version you're using. 

The code is pretty brute: 
1. if the file doesn't exist at the location (local) desired, create it
2. Download it to the local path *always*
3. Verify checksum (error if they don't match)

Because this is a file related question, then the OS gets involved. 
1. What O/S are you using?
2. What are the fully resolved paths?

I looked at the underlying library code and it does attempt to clean the path name, but otherwise there is no logic. It just saves the file. 

turn on `TF_LOG=TRACE` and do some debugging. I don't have enough to go on
