### ISSUE TITLE
Many resources do not support setting a value to its type default

### ISSUE THREAD

**Issue by jamestoyer** [jfrog/terraform-provider-artifactory#228]
**Describe the bug**
There are a number resources that use `omitempty` for optional fields in the API, which means setting the value to the type default fails to set a value in Artifactory. My latest example of this is on `artifactory_user`, but applies to most of the resources I've looked at in the code.

To reproduce, use the following Terraform to create the user. 

```hcl
resource "random_string" "artifactory_password" {
  length = 30
}

resource "artifactory_user" "example" {
  admin                      = false
  disable_ui_access          = false
  email                      = "test@example.com"
  groups                     = ["readers"]
  internal_password_disabled = false
  name                       = "example"
  password                   = random_string.artifactory_password.result
  profile_updatable          = false

  lifecycle {
    ignore_changes = [
      password
    ]
  }
}
```

Then schedule another plan which will show the following.
```hcl
# artifactory_user.example will be updated in-place
  ~ resource "artifactory_user" "example" {
        id                         = "example"
        name                       = "example"
      ~ profile_updatable          = true -> false
        # (5 unchanged attributes hidden)
    }
```

Artifactory version : 7.27.10
Artifactory terraform provider version : 2.6.21
Terraform version : 1.0.11

**Expected behavior**
Fields set to type defaults should be respected and not omitted from the API request.

**Additional context**
Additional linked issues:
- #191 - Another example of this behaviour
- #217 - Fix in a subsequent PR
- jfrog/jfrog-client-go#484 - Underlying client that doesn't support this either, although this project uses a very old version of the library too

I'm going to file a JFrog Enterprise Support ticket about this as it's an active blocker for us upgrading past v2.2 of the provider, something we need to start supporting Cargo repo types correctly in our clusters.

**Comment by chb0github** [comment]
You are completely right. If we were to simply remove all of those it would alter behavior significantly and we would have to know that the "default" value would be to make sure we could maintain backward compatibility. 

All of those `omitempty`s are legacy. If you provide specific cases, we can supply specific solutions. I'm sorry it can't be a broad bases solution

**Comment by jamestoyer** [comment]
If those `omitempty`s were from the legacy code, then I suspect something major has changed in the way the values are sent. For example, 2.2.13 will apply correctly and not produce diffs, like the one mentioned above, whilst 2.6.21 does. I can go through and find other specific cases this this one and #217, but at this point I'd argue that whatever happened after the 2.2.x series is actually a breaking change in the expected contract

**Comment by chb0github** [comment]
I say legacy because, I didn't fully understand what was being attempted in the original code in some places. And, so when moving to the new client I just kept as much as possible as is. I mean, in version 2.2.x, 60% of the tests didn't pass so there was no telling what was going on.

`2.3.x` was a major departure because all of the original atlassian code was pitched away along with all the other hodgepodge code from various client implementations. Along the way, it was discovered that some forms of backward compatibility couldn't be maintained. But, that's was a semantic version bump means: Backward compatibility may have broken (and, when I released, I was sure it was broken). 

From a time and focus perspective, we can fix an issue as it's identified because it limits scope. 

As a side note: We are working on implementing a provider for projects and a dedicated one for xray using current APIs. When that happens, we will phase out xray support here and do a version bump again

**Comment by jcogilvie** [comment]
Is this issue being used to track the specific case of `profile_updatable` or should we file a new issue for that?

**Comment by alexhung** [comment]
@jcogilvie Please open separate ticket(s) for each attribute/value that affect you. This will allow us to better track the changes and easier to manage the work.

**Comment by alexhung** [comment]
Closing this issue. If you have specific attributes that need fixing due to this problem, please open individual ticket for each attribute/resource.
