### ISSUE TITLE
Value for unconfigurable attribute

### ISSUE THREAD

**Issue by vasanthig21** [jfrog/terraform-provider-artifactory#252]
While upgrading jfrog/artifactory to latest version 2.6.23, I am getting the below error.  I appreciate, your suggestions to fix this issue. 

<img width="1249" alt="Screen Shot 2021-12-17 at 1 01 45 AM" src="https://user-images.githubusercontent.com/94625595/146498080-13a8a188-62dc-4db5-802b-859ab97c24f5.png">
>Here is the resource block where the error showing up

<img width="1474" alt="Screen Shot 2021-12-17 at 1 11 23 AM" src="https://user-images.githubusercontent.com/94625595/146498233-18190109-046d-46e0-9c62-254a1489e561.png">

>attaching main.tf where random_password resource was added

<img width="847" alt="Screen Shot 2021-12-17 at 1 05 20 AM" src="https://user-images.githubusercontent.com/94625595/146498416-4ec9faef-514c-4f2f-9389-e2b839ab12fb.png">

**Comment by chb0github** [comment]
#246 - is directly related. There was a long discussion in #20 on this issue but I will summarize: once the password is set, the value it gets back from RT for this field is encrypted (not hashed) and without extracting the master key from the RT host it can't be decrypted (or encrypted) and thus it's state will never be in line with what TF has. 

If a user consensus can be reached on this issue, we can revisit. @alexhung

**Comment by alexhung** [comment]
@vasanthig21 @korjek @michael-sabrnak-swi As you are the ones who have expressed wish to change the provider behavior for this, let's have the discussion here.

@korjek suggested in #246 the use of `ignore_changes` to ignore the value from Artifactory after initial run. While this works for the creation of the resource, it won't allow updating of the password.

Is this a workable solution?

If not, what are your use cases?

**Comment by chb0github** [comment]
We are happy to engage the community but we need to have multiple user input on this.

**Comment by korjek** [comment]
> @vasanthig21 @korjek @michael-sabrnak-swi As you are the ones who have expressed wish to change the provider behavior for this, let's have the discussion here.
> 
> @korjek suggested in #246 the use of `ignore_changes` to ignore the value from Artifactory after initial run. While this works for the creation of the resource, it won't allow updating of the password.
> 
> Is this a workable solution?
> 
> If not, what are your use cases?

@alexhung I agree that using `ignore_changes` is not perfect. But for me it looks more attractive than having to go and update passwords for all replications once replication config is created by terraform. And when someone needs to update password for replication, possibly that can be done by tainting replication resource (forcing it to be recreated with a new password in that way).

**Comment by chb0github** [comment]
@korjek - thanks for the input. We are going to need some more commentary before we can reopen this can-of-worms. @vasanthig21 - comments?

**Comment by korjek** [comment]
another point to add (we faced with this), once replication is configured for the first time for a new repo, there is no password specified, but replication is already working. This makes replication user to be blocked eventually (as replication tries to authenticate with an empty password) and this breaks _all_ replications.

**Comment by pbecotte** [comment]
Hi, just came across this today. The typical pattern for passwords is to just store them in state as is and ignore the value returned from the api- most apis don't have a function to return the value at all, encrypted or not. That of course means that you can't check for drift, but that's just the expected behavior. You can still check if it `HasChange` - if the input value is different from whatever it was last time- you just never update the value in state after an api call. For examples, take a look at the aws provider RDS instance "master_password" (https://github.com/hashicorp/terraform-provider-aws/blob/4dc04258939ffec3feacaee5af04d0301362d269/internal/service/rds/cluster.go) - there are a number of examples of the pattern across the AWS provider.

As a slightly less directed comment- the docs still have the note about the enryption api and list password as an argument, which results in a lot of confusion even if you decide to leave the password field as computed.
