### ISSUE TITLE
Password is mandatory, breaks existing users

### ISSUE THREAD

**Issue by ShreyasNBS** [jfrog/terraform-provider-artifactory#283]
**Describe the bug**
This is in relation to issue [260](https://github.com/jfrog/terraform-provider-artifactory/issues/260) which I believe was incorrectly fixed in 2.9.1. I have hundreds of users in our production artifactory instance, and upgrading to 2.9.1 is forcing me to set passwords for all of them. I could import all the existing users into terraform state, but that's a lot of additional work.
Is there any reason as to why password was made mandatory, when the auto-generation functionality (with passwords being optional in tf code) was working?
This is also preventing me in upgrading to 2.9.1 and make use of the email_attribute fix for LDAP settings.

**Comment by chb0github** [comment]
So, RT requires a password. That has nothing to do with the TF provider. 

If I am understanding you correctly, You want to manage your new users in TF, and leave your old ones alone? I mean, you wouldn't be running into this issue if you didn't have a user resource defined - so, it seems like that's what you're trying to do

Can you give us a sample of your HCL so we aren't speaking in abstracts?

**Comment by ShreyasNBS** [comment]
They all have passwords set it RT. I believe the previous implementation of the provider used to auto-generate password if none was supplied? Happy to be corrected. I create users as such

![image](https://user-images.githubusercontent.com/56643631/151348978-b66dcc64-b2a9-4cc9-b94f-f0adbada4871.png)

Prior to 2.9.1, this worked flawlessly. The old docs suggested that the provider did not store the state of the password, and if a password was not supplied, it would be auto-generated? (I might not be remembering things correctly though). Once the users were created in RT, I would login to UI, and set a password for that user, and share it with our customers. 

After 2.9.1, it now expects "password" field to be mandatory, which means even if the password is set for that user in RT, it gives an error on the lines of "password is mandatory", because tfstate does not have entry for the password field.

**Comment by chb0github** [comment]
The provider, about a year ago, would autogen a password for you - but this had the problem of potentially not lining up with password policy changes. So, it was removed and punted to the user in TF - and examples for generating passwords was supplied. 

Now I get you. And, there is no way to get password (even in hashed form) 

Create needs 1 behavior, and update needs another. RT definitely requires a password, so it's not "optional"

@alexhung - I think we have to punt to RT entirely on password. We can add a validator that doesn't error, but simply warns if the password isn't set. I think we need to set password to Optional (client side) but required server side. I think we need to get entirely out of the password business

**Comment by alexhung** [comment]
> I think we need to get entirely out of the password business

That I agree 100% @chb0github

**Comment by tjstansell** [comment]
FWIW, we added a 
```
  lifecycle {
    ignore_changes = [password]
  }
```
block to all of our `artifactory_user` resources and use the `random_password` resource to provide terraform with an initial password.  Basically, it gives terraform the requirement, but then users change it after the fact and terraform ignores those.  Luckily this works for us, but it's likely not for everyone.

It was definitely a surprise to find a breaking change in a patch release.  It would have been helpful to at least rev the version appropriately when you break things.

**Comment by ShreyasNBS** [comment]
> FWIW, we added a
> 
> ```
>   lifecycle {
>     ignore_changes = [password]
>   }
> ```
> 
> block to all of our `artifactory_user` resources and use the `random_password` resource to provide terraform with an initial password. Basically, it gives terraform the requirement, but then users change it after the fact and terraform ignores those. Luckily this works for us, but it's likely not for everyone.
> 
> It was definitely a surprise to find a breaking change in a patch release. It would have been helpful to at least rev the version appropriately when you break things.

This is great for new users, but it's a forced password change for existing users, which is not at all workable in an enterprise/distributed team environment sadly. I want to retain passwords for existing users :)

**Comment by alexhung** [comment]
> It was definitely a surprise to find a breaking change in a patch release. It would have been helpful to at least rev the version appropriately when you break things.

If you take a look at the [change in 2.9.1](https://github.com/jfrog/terraform-provider-artifactory/commit/c41c94b15b3f5fb534388e82be51a7f9fd969d71#diff-f053b5f72ce64b8f35afd03216e418f66f8b836b2426fbc8a897c38e6c4dc548L69), we changed from [validating password with some criteria](https://github.com/jfrog/terraform-provider-artifactory/blob/c41c94b15b3f5fb534388e82be51a7f9fd969d71/pkg/artifactory/validators.go#L506), to validating the password is not empty. This is a relaxation of validation and is a backward-compatible change.

The breaking change happened last year back in v2.2.15. In hindsight, we should have bumped to v3.x then.

**Comment by tjstansell** [comment]
I beg to differ.  That change in 2.9.1 changed `password` from `Optional: true` to `Required: true`.

**Comment by alexhung** [comment]
@tjstansell You're right. I missed that.

**Comment by jcogilvie** [comment]
> @alexhung - I think we have to punt to RT entirely on password. We can add a validator that doesn't error, but simply warns if the password isn't set. I think we need to set password to Optional (client side) but required server side. I think we need to get entirely out of the password business

If I understand correctly, "optional client side and required server side" is exactly how this was behaving prior to 2.9.1, which was just another kind of broken.  

When attempting to add a new user, the client was passing validation, but the apply was failing to create a new user because password was missing.  Hence #260.  

IMO the 'best' behavior out of all the bad options here is to revert to this:

> The provider, about a year ago, would autogen a password for you - but this had the problem of potentially not lining up with password policy changes. 

Or at least provide a flag to revert to that behavior with a well-documented caveat that a provider-generated password won't necessarily conform to policy.  Or a flag to enforce change on first login, in which case the policy is barely relevant.

The reason I say this is the best option is that it's an edge case failure that doesn't actually *break* anything, whereas 2.9.1+ is a contract change that breaks existing users and pre-2.9.1 is a mismatched contract between client and server which sort of breaks new user creation.

I understand how frustrating this must be for you all, and I'm happy to talk through any options or proposals you have.

**Comment by blyles** [comment]
Just happened to find this after 2.13.0 came into our releases - we didn't notice the disable UI becoming true by default, it kicked in and force reset several accounts to a password that was specified as a var.  We weren't fully aware of the changes in password flow admittedly, assuming that it wouldn't reset the password on the next go round.

After the pipeline ran we had a result of resetting several of our service accounts setting to the default new user pw breaking a lot of pipelines.

Our flow was "onboard new user in tf via pipeline-> user or/admin changed their password post login", state of the user rarely changed until this disable UI dropped in 6 days ago changing the state of artifactory_user so we probably should have seen and caught this earlier.  It seems our flow was used for service accounts as well, wrong or right it was pre-2.9.1.

What we're eyeing to do is onboarding with a pre-set new user password and reset after the fact, I'm looking at how to prevent the tf causing a pw reset, is this possible with the new flows? and forced options?  I'm looking at this ignore_changes field as a possible option.

Because our users went to reset their passwords back, am i just waiting for another pw reset through tf if a property changes again?

**Comment by ShreyasNBS** [comment]
Any ETA on this sirs? :)

**Comment by alexhung** [comment]
@ShreyasNBS No ETA but this is on my agenda this/next week.

**Comment by chb0github** [comment]
Before beginning work @alexhung , let's list out here, in the ticket, the exact behaviours to be implemented or removed, since there has been a lot of suggestions/ideas. Then @jcogilvie @blyles and @ShreyasNBS can agree. 

This has been a real headache for us, and we want to do what's going to work best for our community base. But, we didn't have enough data points and use cases to even consider to make an informed decision

**Comment by ShreyasNBS** [comment]
Honestly, I think the best outcome to rever back to what it was a year ago. Do not check on client or server side, and autogenerate one if not supplied. Job done 👯

**Comment by spuder** [comment]
We just upgraded form 2.6.x to 2.10.x and are running into this where passwords are now required. 


## Workaround
1. Set a new random password 
2. Ignore future changes to the password

```
resource "random_password" "password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "artifactory_user" "conan-read" {
  name              = "conan-read"
  email             = "artifactory@example.com"
  groups            = ["conan-read", "readers"]
  disable_ui_access = true
  password          = random_password.password.result
  lifecycle {
    ignore_changes = [password]
  }
}
```

Note, that this doesn't actually _change_ the password to the random string since the password is ignored. It just makes terraform happy

**Comment by ShreyasNBS** [comment]
@alexhung Can we please roll this back to how it was a year ago? It would be massively useful. This is blocking us from using the new LDAP resources, due to manager password not being set correctly.

**Comment by akashgupta-nbs** [comment]
We just tried above solution of ignore life cycle changes and expected it to ignore password field for all existing users but sadly it seems its updated password in our dev env.. We are upgrading TF provider version from 2.9.0 to 2.24.0 ..wondering how did it work for you @spuder .. is it because we never had password attribute for artifactory users when we created initially..? any thoughts?

**Comment by ShreyasNBS** [comment]
> This is high on our priority list. Alex should be back in the game soon and we'll work to resolve this

Please do this on high priority as mentioned. We have an urgent need to create php composer remote repos, and they are not supported by old artifactory_remote_repository resource. So we will need to upgrade to latest version, and the ignore_changes bypass is not working for us (We tried and it changed the password of existing users) as @akashgupta-nbs  mentioned.

**Comment by chb0github** [comment]
I'm going to advocate for a rapid iteration approach since it has complexities. We have an open discussion on this matter, so any input you'd like to give is welcome. Everyone on this issue should give their input

https://github.com/jfrog/terraform-provider-artifactory/discussions/333

**Comment by akashgupta-nbs** [comment]
@chb0github  do we have any updates here? Its really blocking us to move to new jfrog tf provider and impacting other good features you guys have worked on.. I would appreciate if you can suggest how can we upgrade provider here without breaking the existing functionality. Before this change we had AF user created through tf block without password but with this change, it seems its mandatory to give password field for exiting users which would require to change password for each user which we never maintained in tf state file earlier as it was optional earlier i believe..

**Comment by alexhung** [comment]
@akashgupta-nbs You follow updates and discussion at https://github.com/jfrog/terraform-provider-artifactory/discussions/333
