### ISSUE TITLE
GPG key support for repos

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#285]
**Is your feature request related to a problem? Please describe.**
I want to fully-automate the configuration of my Artifactory cluster using Terraform, which includes GPG keys.

**Describe the solution you'd like**
Implement support for GPG keys in [artifactory_keypair](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_keypair).

**Describe alternatives you've considered**
Falling back to a [`local-exec` provisioner](https://www.terraform.io/language/resources/provisioners/local-exec)

**Additional context**
https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/resource_artifactory_keypair.go#L47-L54

**Comment by chb0github** [comment]
When I first wrote the code I wanted to support GPG, but the lib support for it in go was crap and I was having issues. As it wasn't essential for the task at hand, I punted.

**Comment by skyzyx** [comment]
Makes sense.

I'm trying to move as much of our cluster config into code as possible, so that we have a better audit trail for changes besides attempting to grep through the massive log files.

Anything I can't do in Terraform, I'm falling back to curl calls to the API. I'm hoping to reduce those cases to as close to zero as possible.

**Comment by skyzyx** [comment]
> […] but the lib support for it in go was crap […]

Are you trying to perform client-side validation _before_ pushing it up to the server? If so, wouldn't the server do this anyway? Is this something that can offloaded?

**Comment by chb0github** [comment]
yes, our game plan is to do as much client side validation as possible. Experience has shown the RT will accept junk and fail later and we never known when/where until we stumble on it. 

Honestly, I couldn't tell if there was a problem with my keys or not - I had real difficultly getting GPG keys created (in RT, even through the UI) and because I couldn't independently verify the keys in code, I couldn't be sure if it was failing validation server side or I was calling the API wrong or what. 

The way RT handles keys is really odd. You actually have to send them as base64 text, but with newlines actually in the payload. It makes no sense. But, that how it works

**Comment by alexhung** [comment]
@skyzyx I looked into this couple of week ago as part of #303. I updated the tests and fixed how the keys are stored in the state file. Hopefully this will work like you want.
