### ISSUE TITLE
Terraform fails to init while using a module.

### ISSUE THREAD

**Issue by KrystianMarek** [jfrog/terraform-provider-artifactory#29]
This is a followup to https://github.com/jfrog/terraform-provider-artifactory/issues/26 
I created a git repo with code example - https://github.com/KrystianMarek/bug-terraform-artifactory-provider 

As described in the readme, when a module is used https://github.com/KrystianMarek/bug-terraform-artifactory-provider/blob/main/main.tf#L13 terraform init fails.

**Comment by hammopau** [comment]
I believe you need to
1) Define the artfactory provider again in the module where the provider is actually used:
.../modules/core/main.tf:
terraform {
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
      version = "2.2.5"
    }
  }
}

2) Pass in the authenticated artifactory provider from main.tf as its not inherited (only default providers are inherited - dont ask as I havnt looked :) ).  You dont need another 'provider "artifactory" {}' in sub-modules (iirc TF doesnt like this & complains).

.../main.tf:
module "core" {
  source = "./modules/core"
  
  providers {
    artifactory = artifactory
  }
}

The good news is that you only have to auth once into the .../main.tf provider & then reuse as above as needed.

The above worked for me, but I'm sure some kind person can correct if this is the wrong approach...

**Comment by KrystianMarek** [comment]
Hi @hammopau, thanks, indeed `terraform init` worked, I just had to update /main.tf with
```
module "core" {
  source = "./modules/core"
  providers = {
    artifactory = artifactory
  }
}
``` in order to make the `terraform plan` work as well

**Comment by chb0github** [comment]
@KrystianMarek - based on your most recent comment, am I am to assume you've resolved your issue?

**Comment by KrystianMarek** [comment]
I would consider it more like a workaround, it works for me with the updates suggested by @hammopau . I leave it up to you @chb0github if you want to fix it or ignore it.

**Comment by peters95** [comment]
What happens if no module is used and this is added. Does it break? If not we can merge, otherwise this should be up to the person who decided to use the additional feature of Terraform modules.

**Comment by hammopau** [comment]
I just upgraded to 0.14.6 (from 0.14.5) and the problem of the provider not being passed as expected between parent & child modules appears to have been resolved in this release (or so I thought - see below).  I now have both modules declaring artifactory as required_plugin, but only configuring "provider artifactory {}" in the parent, and all is working ok.

I also tested with 0.13.6 & its also ok with the 'correct' config.  To try and figure out where the problem was, I tested with 0.14.5 again (as used when I first figured out passing the provider fixed the issue), just to see if it was a TF issue & thats also working now, whereas it was not previously...

...confused_dot_com...
