### ISSUE TITLE
artifactory_file read error

### ISSUE THREAD

**Issue by scottwinkler** [jfrog/terraform-provider-artifactory#3]
The file I am trying to read from does not have a sha256 set. So in my response object I only get the other two checksums:

```
  "checksums" : {
    "sha1" : "293ddf0e11093b420f312f83ceaf5b476560ecea",
    "md5" : "5e49fbfd88d2204b6a1cbbd70872c07a"
  },
```

This gives me a runtime error:

```
data.artifactory_file.my-file: Refreshing state...

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2020-10-23T04:12:42.662-0700 [DEBUG] plugin.terraform-provider-artifactory_v2.2.4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1c246cd]
2020-10-23T04:12:42.662-0700 [DEBUG] plugin.terraform-provider-artifactory_v2.2.4:
2020-10-23T04:12:42.662-0700 [DEBUG] plugin.terraform-provider-artifactory_v2.2.4: goroutine 31 [running]:
2020-10-23T04:12:42.662-0700 [DEBUG] plugin.terraform-provider-artifactory_v2.2.4: github.com/atlassian/terraform-provider-artifactory/pkg/artifactory.dataSourceFileRead(0xc0002a6770, 0x1cc45c0, 0xc0008e3d00, 0x0, 0x0)
2020-10-23T04:12:42.662-0700 [DEBUG] plugin.terraform-provider-artifactory_v2.2.4: 	github.com/atlassian/terraform-provider-artifactory/pkg/artifactory/datasource_artifactory_file.go:97 +0x26d
```

recommend either making the sha256 checksum optional, or at least make the error message more clear.

**Comment by chb0github** [comment]
@scottwinkler - can you please supply me with a terraform file that demonstrates this issue? I mean, I see the code but wouldn't expect an error.

If I don't hear back soon, I will close the issue on the assumption it's obsolete

**Comment by scottwinkler** [comment]
still getting error message.
error is happening on line 97 https://github.com/jfrog/terraform-provider-artifactory/blob/master/pkg/artifactory/datasource_artifactory_file.go#L97
```
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "~> 2.0"
    }
  }
}

provider "artifactory" {
  url = "${var.artifactory_url}/artifactory"
  username = var.artifactory_username
  password = var.artifactory_password
}

data "artifactory_file" "my-file" {
   repository = "deploy"
   path = "<artifact path>"
   output_path = "artifact.zip"
}
```

**Comment by chb0github** [comment]
@scottwinkler 

To help repo this, I need this to know
1. What version of artifactory you're running 
2. what version of terraform are you using
3. And, I noticed that the provider version you have listed is non-specific. Can you please hard-code to the latest version `2.2.5` and see if you get the same issue?

To get your version of RT, you can go to this url:
`${host}/artifactory/api/system/version/ `

**Comment by scottwinkler** [comment]
1) Artifactory version 4.12.0.1
2) Terraform v0.14.7
3) ~> pulls latest provider version, which is what i was using

**Comment by markgalpin** [comment]
@scottwinkler Artifactory 4.12.x was declared [EOL](https://www.jfrog.com/confluence/display/JFROG/Artifactory+End+of+Life) on March 1, 2018.  One of a number of issues with Artifactory 4.12 is that it is still relying on SHA1 instead of SHA256 -- which, because SHA1 can be spoofed for an arbitrary document, is considered a security risk, and we won't be making SHA256 support optional for the provider.  We introduced SHA2 support to Artifactory in Artifactory 5.5 in September of 2017.

We strongly recommend you upgrade to version 7.x of Artifactory.  If you have a pro instance, [upgrading will take longer](https://www.jfrog.com/confluence/display/RTF5X/Release+Notes) as it calculates SHA2 checksums.  If you have an HA instance please see [artifactory 5.5 upgrade notice](https://www.jfrog.com/confluence/display/RTF5X/Release+Notes#ReleaseNotes-UpgradeNotice.1).  [Then to 6.10.x](https://www.jfrog.com/confluence/display/JFROG/Upgrading+Artifactory#UpgradingArtifactory-UpgradingfromVersionBelow6.10), and then on to RT 7.x.

In addition to the SHA2 support, newer versions of Artifactory contain many significant enhancements to performance, quality of life, and support for additional package types, as well as addressing a number of security issues with the system.

In general, if you have a current support subscription, JFrog support will be happy to walk you through the steps of upgrading.  Closing this issue, but feel free to comment if you have additional questions.
