### ISSUE TITLE
project key and project environment arguments support for local docker v2 repository.

### ISSUE THREAD

**Issue by yash95shah** [jfrog/terraform-provider-artifactory#327]
https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_local_docker_v2_repository

Can we have all the arguments from the Jfrog API configurable especially project key and environment?

**Comment by alexhung** [comment]
@yash95shah while the documentation doesn't include `project_key` and `project_environments` attributes, they are part of all local repository resources (except legacy `artifactory_local_repository`) released in [v2.19.0](https://github.com/jfrog/terraform-provider-artifactory/blob/master/CHANGELOG.md#2190-feb-16-2022).

**Comment by martinm82** [comment]
@alexhung are there plans to get rid of `artifactory_local_repository`? We are starting to use the Terraform provider for configuring Artifactory and have currently a mix of both (special purpose repo resources and the local one). The reason is that certain attributes cannot be set in the special purpose ones and from the REST API it is not clear which attributes/fields are relevant for the specific repositories (a JFrog support ticket is already open for this).

If you would say that the legacy resource is going to be removed soon then we will not use it, especially because we saw in other tickets that migrating from one resource type to another causes destruction of the repositories which in our case would be kind of a disaster :)

**Comment by martinm82** [comment]
Are you sure the new feature actually works? We are using Artifactory Cloud 7.34.4 and encountered the problem that the repository is not assigned to a project. After running tf apply it says all changes were applied but running it again it shows that the changes (project_key) will be applied again.

In the TF logs we see the following error:

```
2022-02-22T15:25:48.792+0100 [WARN]  Provider "provider[\"registry.terraform.io/jfrog/artifactory\"]" produced an unexpected new value for artifactory_local_helm_repository.del_team_x_helm_local, but we are tolerating it because it is using the legacy plugin SDK.                    The following problems may be the cause of any confusing errors from downstream operations:
      - .project_key: was cty.StringVal("del"), but now cty.StringVal("")
```

**Comment by martinm82** [comment]
Is this a problem of the Terraform version (1.0) we use?

**Comment by alexhung** [comment]
@martinm82 Let me take a look.

**Comment by alexhung** [comment]
@martinm82 The plan is to provide feature-completed repo type specific resources. Once that's done, we will deprecate the one-size-fit-all `artifactory_local_repository`, `artifactory_remote_repository`, `artifactory_virtual_repository` resources.

So yes, please avoid using the 'legacy' `artifactory_local_repository` resources if possible. And report any missing attribute support for repo type specific resource so we can add them.

**Comment by alexhung** [comment]
@martinm82 Do you have a list of repo resources and their missing attributes that you want to use? If you create an new issue with them, we can get them fixed for you.
