### ISSUE TITLE
Add ability to configure the webserver via terraform

### ISSUE THREAD

**Issue by tomgeorge** [jfrog/terraform-provider-artifactory#357]
**Is your feature request related to a problem? Please describe.**

I would like to configure the webserver programatically in order to configure subdomain docker access, and to use the NGINX web server.

**Describe the solution you'd like**
I would like to be able to create a terraform resource that controls the webserver configuration per: https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateReverseProxyConfiguration

**Describe alternatives you've considered**

- Manually configuring the webserver in the UI
- Hitting the REST API in a script

**Additional context**
https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateReverseProxyConfiguration

**Comment by chb0github** [comment]
@tomgeorge - Please supply some suggested HCL for your request

**Comment by tomgeorge** [comment]
Based on this example from the docs:

```
POST /api/system/configuration/webServer
{
  "key" : "nginx",
  "webServerType" : "NGINX",
  "artifactoryAppContext" : "artifactory",
  "publicAppContext" : "artifactory",
  "serverName" : "jfrog.com",
  "serverNameExpression" : "*.jfrog.com",
  "artifactoryServerName" : "localhost",
  "artifactoryPort" : 8081,
  "sslCertificate" : "/etc/ssl/myKey.cert",
  "sslKey" : "/etc/ssl/myKey.key",
  "dockerReverseProxyMethod" : "SUBDOMAIN",
  "useHttps" : true,
  "useHttp" : true,
  "sslPort" : 443,
  "httpPort" : 76
}
```

I would think you can map it 1:1 like this:

```hcl
resource "artifactory_webserver" "webserver" {
  key = "nginx"
  artifactory_app_context = "artifactory"
  web_server_type = "NGINX",
  artifactory_app_context = "artifactory"
  public_app_context = "artifactory",
  server_name = "jfrog.com",
  server_name_expression = "*.jfrog.com",
  artifactory_server_name = "localhost",
  artifactory_port = 8081,
  ssl_cert_path = "/etc/ssl/myKey.cert",
  ssl_key_path = "/etc/ssl/myKey.key",
  docker_reverse_proxy_method = "SUBDOMAIN",
  use_https = true,
  use_http = true,
  ssl_port = 443,
  http_port = 76
  
}
```

**Comment by chb0github** [comment]
Thanks so much - we'll take it from here.

**Comment by chb0github** [comment]
You've articulated this much better than I have. Just because an endpoint is offered, doesn't mean we should touch it.

I share your concern about zombifying the node. Frankly, the fact that platform microservices are behind nginx is entirely an internal implementation and shouldn't be exposed. By exposing these endpoints the platform team has reduced options for flexibility of they should ever want to change reverse proxies.

**Comment by tomgeorge** [comment]
> With regard to the separation of concerns, I don't believe that configuring the Nginx web server is part of "configuring Artifactory" in the same way as creating repositories and users.

+1. At least in Kubernetes, the jfrog chart gives you an nginx deployment out of the box, so it is maybe a little more tightly-coupled to Artifactory in kube-land than on other deployment platforms.

> Ideally, you'd pre-bake a cloud image (e.g., with Packer, AWS ImageBuilder) with Artifactory and Nginx installed, with the standard configuration between them already set up so that when the node comes online, it already works the way it's supposed to at a web-server level. Less-good, but still an option is one of those post-launch provisioning tools like Ansible/Chef/Puppet.

I agree that this would be the ideal way to do this, but for users running Artifactory in kubernetes like us, we only have the option of manually configuring this in the UI, (possibly) messing with the config descriptor, or rolling our own piece of software to administer Artifactory. We found this provider and thought that it was an awesome piece of software, so we have been trying to push as much of the configuration of Artifactory into terraform.

@chb0github @skyzyx are there any other ways to define Artifactory's config via software? The team that I'm on could write our own app to do this, but that's another piece of code that has to be maintained, tested, supported, etc.

I really wish Artifactory supported more of this configuration in a config-driven way.  AFAIK the config descriptor is a very stateful thing and not something well-suited to automation.

**Comment by skyzyx** [comment]
@[tomgeorge](https://github.com/tomgeorge) said:

> I really wish Artifactory supported installing itself in a config-driven way. AFAIK the config descriptor is a very stateful thing and not something well-suited to automation.

We've run into this too. Having used Artifactory at my last 2 companies (≈8 years), it's not something that has ever been meaningfully improved.

An an outsider, my observation (reading the tea leaves) is that Artifactory was fundamentally built datacenter-style. Even though Amazon EC2 came out in 2006 and Docker ramped-up in the early 2010's, my opinion is that Artifactory has been slow to capitalize on a cloud-first deployment approach. _It can be done_, but I can say that despite my team and I asking our account manager and support team several times, there is not any "blessed" cloud architecture style for running Artifactory.

> […] but for users running Artifactory in kubernetes like us, we only have the option of manually configuring this in the UI, (possibly) messing with the config descriptor, or rolling our own piece of software to administer Artifactory. We found this provider and thought that it was an awesome piece of software, so we have been trying to push as much of the configuration of Artifactory into terraform.

This would be a wonderful thing for Artifactory account managers and any "developer support" folks who may-or-may-not work for JFrog to invest in and provide. I haven't discovered anything of the sort (yet), but I would encourage you to do the same thing we did and apply as much pressure on JFrog as you are able to, in order to _encourage_ them to provide such a thing in a "blessed" way (that you can request Support on, and the Support folks should be _expected_ to be familiar with this so that they can help you).

**JFrog employees: Please cover your ears for a moment.**

I've been having to write a set of automated smoke tests that run against Artifactory to catch when there are breaking changes in minor/patch-level releases. We've encountered several incomplete implementations of APIs/features and breaking changes _during_ the v7 major version release cycle. When I reach out to JFrog Support about broken functionality, changing APIs, and poor/incorrect public documentation, they basically tell me that "[there is no war in Ba Sing Se](https://knowyourmeme.com/memes/there-is-no-war-in-ba-sing-se)."

After we finish our migration from Artifactory v6 → v7, I'm going to begin evaluating (a) [Sonatype Nexus Pro](https://www.sonatype.com/products/repository-pro) for equivalent functionality, an approved cloud-based design, and automation capabilities top-to-bottom, as well as (b) continue pressing our account reps at GitHub to continue expanding [GitHub Packages](https://docs.github.com/en/enterprise-server@3.4/packages/working-with-a-github-packages-registry/working-with-the-docker-registry), including adding support for pass-thru caching on "remote" repositories. GitHub already works in an API-first way. Since we're already GitHub Enterprise customers, we'd have the potential to save 10s-of-thousands of dollars per year on seat licenses.

More competition from bigger players will hopefully either drive JFrog to step it up, or die on the vine.

That said, I think that _this team_ of people working on _this project_ have been busting their asses to make something good — they're just working with the resources they have available. I get that. But things won't change until the people steering the ship start doing better. So I choose to apply most of my pressure _there_.

**JFrog employees: You can uncover your ears now.**

So yeah, @[tomgeorge](https://github.com/tomgeorge), reach out to your support reps and apply pressure for the things that you need, that the product is missing. Vote with your hard-earned dollars, and since the western world is highly capitalistic, I'd encourage everybody else to do the same.

**Comment by alexhung** [comment]
@skyzyx Thank you for the feedback. I'll forward your comment/link to higher management. No promises on results!

**Comment by alexhung** [comment]
@tomgeorge We have decided not to add support for configuring the Artifactory reverse proxy web server. Per discussion, the risk far outweighs the reward.

The `nginx` section in the [JFrog Helm Chart](https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L1473) may be of interest to you? You may need to modify that chart to configure the k8s for your use case.

**Comment by tomgeorge** [comment]
@alexhung and @skyzyx thank you for the discussion. We will try to reach out to our support contacts for something like this. 

Unfortunately the `nginx` section of the helm chart configured the nginx pod that fronts Artifactory, not the configuration of the web server in Artifactory described in this issue
