### ISSUE TITLE
Concerned with major version (breaking) releases in rapid succession

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#393]
**Is your feature request related to a problem? Please describe.**

Good morning. :) Just a friendly note from an engineer to other engineers:

* Major version 3 was released 10 days ago.
* Major version 4 was released 7 days ago.
* Major version 5 was released 16 hours ago.
* Major version 6 was also released 16 hours ago.

From the [Semantic Versioning specification](https://semver.org/#if-even-the-tiniest-backwards-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly):

> **If even the tiniest backwards incompatible changes to the public API require a major version bump, won’t I end up at version 42.0.0 very rapidly?**
>
> This is a question of responsible development and foresight. Incompatible changes should not be introduced lightly to software that has a lot of dependent code. The cost that must be incurred to upgrade can be significant. Having to bump major versions to release incompatible changes means you’ll think through the impact of your changes, and evaluate the cost/benefit ratio involved.

**Describe the solution you'd like**

Bundle-up breaking changes into a single release so that upgrading users only get broken once instead of several times. It might be helpful to release pre-release RCs first so that people can test changes and provide feedback before cutting an official release.

Ideally:

* There would be more rigor in the automated testing to catch things like the basic authentication flip-flops.
* Deeper functionality would be tested. (For example: not just generating Access Tokens, but also testing that the access token can do what it's intended to do.)
* Multiple versions would be tested (perhaps by spinning-up multiple clusters with Terraform and base system images via whatever CI system you use). [I suggested this in a different ticket.]

If the ideal state can't be reached in the relative near-term, then at least _planned_ breaking changes should be bundled together into a single release so that customers are only broken _once_ in a general timeframe rather than several times in quick succession.

Is it a resources issue? As an enterprise customer, is there anything that I can do to apply pressure to the company at a higher level to ensure that adequate testing systems/infrastructure are available for this project?

**Describe alternatives you've considered**

None.

**Additional context**

Again, thank you for your work on this software.

**Comment by chb0github** [comment]
Hey there @skyzyx - We were very congnizent of releasing breaking changes and how fast we were going and I'll give some guidance on what we're trying

1. We intentionally created numerous major releases so that users could pick-and-choose versions, in case they weren't ready. For example, removing all the legacy repos is something that some teams might not be ready for and some have no problem. Teams that aren't ready can stay on that version as long as is needed. 
2. We made the major version changes fully understanding that we might need to monkey patch in features from a different release. 

The release cycle is was very intentional because we had so many backlogged breaking changes and we knew we might be asked to create `x.y.z` `y` releases on any given major version.

We (me personally) value your input and opinion. I mean, our more rigorous documentation and semver release is specifically because of your suggestions.

As for your quote from semver: I wouldn't worry about `42.0.0` release. We have no new major version releases in our pipeline. So, you can expect `6.x.x` to be the major version for the long future. 

If there is a specific test or automation you think we should implement, we'll consider it (for example, you requested that we list the Artifactory version we tested against (and even here, usage of the word `Artifactory` instead of `RT` is your suggestion), and a ticket has been cut and will be worked on soon)

There really isn't anyone you can lean on that you haven't already. Myself and @alexhung are your best resources for changes in any of our providers, and any changes you need in `Artifactory` your only recourse is a support ticket. We have absolutely no extra juice

sidenote: We are working to get a newsletter setup so we can proactively announce changes before release and give our users a chance to speak up. 

Thanks again for your input, and if you wanna show your love, get your friends to give this repo (and our other ones) stars

- @chb0github

**Comment by skyzyx** [comment]
Thanks for the explanation. While unusual, the explanation at least makes sense. I appreciate it.
