### ISSUE TITLE
Allow creating users in OAuth realm

### ISSUE THREAD

**Issue by parviste** [jfrog/terraform-provider-artifactory#479]
**Is your feature request related to a problem? Please describe.**
I'm running JFrog Cloud, and want to be able to manage users and groups through terraform. I want my users to be able to sign in using Github.

**Describe the solution you'd like**
I want to be able to be able to specify the realm when creating an `artifactory_user`.

**Additional context**
The current code at https://github.com/jfrog/terraform-provider-artifactory/blob/f0f0ae0218769a7bf9900ef91ed6f47ce9bb8e6d/pkg/artifactory/resource/user/user.go seems to have some support for setting the Realm, but the schema prevents us from actually setting it in the terraform code.

**Comment by chb0github** [comment]
Well, adding a field to this schema is easy enough. But, how to test it? I'll be the first to admit I am not familiar with setting up an OAuth realm to test against. 

Can you supply us with some HCL that I can use to set this up quickly?

**Comment by parviste** [comment]
I might also be misunderstanding this. Our users sign in using Github, and we want to be able to manage access of these users to our instance. I.e. I want to be able to specify that user X on Github can access our instance. Currently users who have signed up manually show up in the users list with the realm "oauth".

So to test it, I suppose it's enough to just have a test user with a github account?

**Comment by alexhung** [comment]
@parviste The `realm` field in the Artifactory API is a [read-only field](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.User+json). This means it is not possible to specify the realm when managing an user resource in Terraform.

If you wish to manage an user that uses authentication method other than Artifactory, my suggestion is to import the user into your Terraform configuration after they have signed up. Then you can manage their settings afterward.

**Comment by chb0github** [comment]
Ok, upon speaking with @alexhung I think there is some confusion. You're actually asking 2 things here:

1. You want to setup your artifactory instance to auth with oauth 
2. You want to be able to create users with terraform

But, these are not compatible. 

If you create a user with terraform, then you're creating a local user (aka: non oauth). If you enable github oauth, then the user gets created on demand when they first signing up on your artifactory platform and thus, the username, password, etc, is entirely out of your control (that's the point). Where as if you create a local user, you can manage all of that.

You can assign permissions to an oauth user or set a default for them. But the username, etc is managed by your oauth provider. 

You also can't create a local user, say `joe` and then decide to switch him over to being an oauth user because users are managed by your oauth provider. Typically, this sort of thing is done by "linking" a local account with oauth but support no such functionality on the plaform. 

So, I am going to close this ticket because there is really nothing to be done.

**Comment by parviste** [comment]
Hmm, I see. But it does create some suboptimal workflow. We already know in advance who our users are, but not we first have to ask them to sign up, and only then can we grant them permissions. So we can't do it in "one" go, but have to go and import them separately after each one has signed up_

Also, we would now be able to invite users using terraform?

To me it would make sense to then have e.g. an "oath_user" resource, that when created sends out an invite to the user, and when destroyed revokes access for that user. If we could use the resource to configure permissions already before the user has accepted the invitation that would be great.

Right now it seems there are some things I can't do with terraform that I really expected I would have.
