### ISSUE TITLE
Add retry/refresh for async operations

### ISSUE THREAD

**Issue by mcaulifn** [jfrog/terraform-provider-artifactory#545]
**Describe the bug**
If there are async operations occurring, the provider should account for that. 

Example:
When creating a user, scoped token, and smart remote repository, the repo creation fails with error below. A second apply will succeed.

TF:

```hcl
terraform {
  required_version = "1.2.6"

  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "6.15.1"
    }
    project = {
      source  = "registry.terraform.io/jfrog/project"
      version = "1.1.6"
    }
  }
}

provider "artifactory" {
  url          = "https://${var.artifactory_hostname}/artifactory"
  access_token = var.access_token
}

provider "project" {
  url          = "https://${var.artifactory_hostname}/artifactory"
  access_token = var.access_token
}

resource "artifactory_user" "sync" {
  name  = "sync-user"
  email = "noreply@blah.biz"

  groups = [
    "readers",
  ]
}

resource "artifactory_scoped_token" "sync" {
  scopes   = ["applied-permissions/user"]
  username = artifactory_user.sync.name
}

resource "artifactory_remote_docker_repository" "this" {
  key                           = "project-docker"
  block_pushing_schema1         = true
  enable_token_authentication   = true
  external_dependencies_enabled = true
  list_remote_folder_items      = true
  password                      = artifactory_scoped_token.sync.access_token
  project_environments          = ["PROD"]
  project_key                   = "project"
  propagate_query_params        = true
  store_artifacts_locally       = true
  url                           = "${local.remote_url_prefix}/docker/project-docker"
  username                      = artifactory_user.sync.name

  content_synchronisation {
    enabled                         = true
    statistics_enabled              = true
    properties_enabled              = true
    source_origin_absence_detection = true
  }
}
```

```
 Error:
│ 400 POST https://saas.jfrog.io/artifactory/api/repositories/packages-docker
│ {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "Upstream repository credentials or user permissions insufficient"
│   } ]
│ }
│
│   with module.smart_remote["packages"].artifactory_remote_docker_repository.this,
│   on .terraform/modules/smart_remote/docker.tf line 1, in resource "artifactory_remote_docker_repository" "this":
│    1: resource "artifactory_remote_docker_repository" "this" {
```

Artifactory cloud version: 7.39.10

**Requirements for and issue**
- [ ] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**
The provider should verify token creation has completed successfully before considering resource creation complete.

**Additional context**

**Comment by chb0github** [comment]
@mcaulifn - The way terraform manages resource and state means that each resource knows nothing about the other. So, when TF attempts to invoke the code to create the repo, it gives no hint at all that your tried to create a token, much less that you've associated it with the repo. That means that, logically, the internal code has no way of knowing which resource to check for completion. 

Now, that being said, the scoped tokens all have a certain "look and feel" and, technically that value could be inspected and determined to be a token, which could then be tested (by attempting to create a dummy repo??). It makes a lot of assumptiions. Basically, this could be hardcoded but runs the risk of failure in the future if the artifactory team changes the look and feel of the tokens. 

Alternatively, @alexhung you could probably use the built-in retry logic to handle this case since it seems super clear. 

Both solutions are hacky, but the second one is a hack that's well tread for getting around similar problems. Really, this would be a fix on the artifactory team

**Comment by alexhung** [comment]
@mcaulifn Something else to keep in mind. The micro-service architecture (I know Artifactory is still somewhat monolithic) means that some of the states are not up-to-dated instantaneously. Currently there isn't any way to know when this eventual consistency is reached through the API so the retry mechanism that @chb0github mentioned will be the path to take for now.

**Comment by chb0github** [comment]
BTW: Your `url` includes `/artifactory` which is ignored, since the endpoints for any given resource in artifactory does not have a consistent endpoint. As a result, the only thing that can be used is host.

https://github.com/jfrog/terraform-provider-shared/blob/main/client/client.go#L14-L20
