### ISSUE TITLE
`make doc` fails to automate generation of documentation

### ISSUE THREAD

**Issue by mdb** [jfrog/terraform-provider-artifactory#552]
**Describe the bug**
The `GNUMakefile` contains a `doc` target, which invokes `go generate`. Presumably, this is intended to utilize [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) towards the goal of automating the generation of `terraform-provider-artifactory` markdown documentation, as is convention among Terraform providers.

However, it seems `make doc` has no impact on the markdown documentation in `docs` fails to automate the generation of documentation (am I mistaken?).

**Expected behavior**
I would expect to see the markdown files in `docs/*` updated, following output like...

```
go generate ./...
rendering website for provider "terraform-provider-artifactory" (as "terraform-provider-artifactory")
copying any existing content to tmp dir
exporting schema from Terraform
compiling provider "artifactory"
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
getting provider schema
rendering missing docs
generating missing resource content
...
```

Thanks!

**Comment by alexhung** [comment]
@mdb We started using the doc plugin for the other providers (xray, project, pipeline) with success since they are new providers, and therefore we don't have to migrate existing content. This is despite the few bugs in the doc plugins that we have to manually deal with after doc generation.

When we attempted to implement the doc plugin for artifactory provider, these bugs (along with the fact that most of the existing resources don't have `Description` field that the plugin relies on) means that we will provide just as many static documentation Markdown files as pre-doc plugin. We decided then to suspend that effort until 1) doc plugins bugs are fixed, and 2) we have retrofit `Description` field to all the resources.

From my chat with HashiCorp engineers last week at HashiCorp Partner Summit, they assured me that the doc plugin is being worked on and bug fixes are forthcoming. So at some near future, we will finish retrofitting `Description` fields and be able to auto-gen the documentation.

**Comment by mdb** [comment]
@alexhung Thanks for the context! In the intermediary, I wonder if there's a way to make all this more discoverable to contributors? I myself burned quite a bit of time on this when cooking up https://github.com/jfrog/terraform-provider-artifactory/pull/551 :)
