### ISSUE TITLE
Artifactory provider plugin crashes with multiple module calls

### ISSUE THREAD

**Issue by aisvarya2** [jfrog/terraform-provider-artifactory#679]
**Describe the bug**
terraform-provider-artifactory plugin crash.

**Requirements for and issue**
- I'm trying to create a module for repo creation in artifactory. There are 60+ repos. For creating each repo an individual module call will be created. When calling these repos using module calls, terraform plan succeeds but the terraform apply fails with **"plugin crashed error"**. Whereas, if the resources are created directly then all the 60+ repos are created without any issue. Plugin crash occurs when there is a separate module call for each repo.

terraform code to reproduce the bug.

This is the module structure to create the project and repos 
├── artifactory-projects
│   ├── main.tf
│   ├── outputs.tf
│   └── variables.tf
└── artifactory-repos
    ├── main.tf
    ├── outputs.tf
    └── variables.tf

The file to call the modules 
[sample_code.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10883270/sample_code.txt)

Module file for project creation
[main.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10883320/main.txt)

Module file for repo creation
[main.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10883353/main.txt)

I tired to apply the configuration with both version 6.19 and 7.0 with both the versions the plugin crashed. Attaching the log file too.

[artifactory plugin crash log.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10883429/artifactory.plugin.crash.log.txt)

**Expected behavior**
Repos to be created seamlessly without plugin crash when there is multiple module calls.

**Comment by alexhung** [comment]
@aisvarya2 Since the files you provided do not contain the full set, I have to recreate my own set of modules (based on yours). As the error in the logs shows a crash originates from the virtual repo resource, I defined a module with set of local, remote, and virtual docker repos.

`main.tf` in root directory:

```hcl
module "local-docker" {
  source = "./modules/repos"
  local_docker = {
    key = "docker-local"
    description = "Test description"
    xray_index = true
    docker_tag_retention = 3
    docker_max_unique_tags = 1
  }
}

module "remote-docker" {
  source = "./modules/repos"
  remote_docker = {
    key                         = "docker-remote"
    description                 = "Test description"
    xray_index                  = true
    enable_token_authentication = true
    url                         = "http://tempurl.org"
  }
}

module "virtual-docker" {
  source = "./modules/repos"
  virtual_docker = {
    key                     = "docker-virtual"
    description             = "Test description"
    repositories            = [module.local-docker.local_docker_key, module.remote-docker.remote_docker_key]
    default_deployment_repo = module.local-docker.local_docker_key
  }
}
```

`main.tf` from `./modules/repos`:

```hcl
terraform {
  required_providers {
    artifactory = {
      source  = "jfrog/artifactory"
      version = "~> 7.0"
    }
  }
}

resource "artifactory_local_docker_v2_repository" "this" {
  count                = var.local_docker != null ? 1 : 0
  key                  = var.local_docker.key
  description          = var.local_docker.description
  xray_index           = var.local_docker.xray_index
  tag_retention        = var.local_docker.docker_tag_retention
  max_unique_tags      = var.local_docker.docker_max_unique_tags
}

resource "artifactory_remote_docker_repository" "this" {
  count                       = var.remote_docker != null ? 1 : 0
  key                         = var.remote_docker.key
  description                 = var.remote_docker.description
  xray_index                  = var.remote_docker.xray_index
  enable_token_authentication = var.remote_docker.enable_token_authentication
  url                         = var.remote_docker.url
}

# virtual docker
resource "artifactory_virtual_docker_repository" "this" {
  count                   = var.virtual_docker != null ? 1 : 0
  key                     = var.virtual_docker.key
  description             = var.virtual_docker.description
  repositories            = var.virtual_docker.repositories
  default_deployment_repo = var.virtual_docker.default_deployment_repo
}
```

`variables.tf` in `./modules/repos`:

```hcl
variable "local_docker" {
    type = object({
        key = string
        description = string
        xray_index = bool
        docker_tag_retention = number
        docker_max_unique_tags = number
    })
    default = null
}

variable "remote_docker" {
    type = object({
        key = string
        description = string
        xray_index = bool
        enable_token_authentication = bool
        url = string
    })
    default = null
}

variable "virtual_docker" {
    type = object({
        key = string
        description = string
        repositories = list(string)
        default_deployment_repo = string
    })
    default = null
}
```

`outputs.tf` in `./modules/repos`:

```hcl
output "local_docker_key" {
    value = length(artifactory_local_docker_v2_repository.this) > 0 ? artifactory_local_docker_v2_repository.this[0].key : null
}

output "remote_docker_key" {
    value = length(artifactory_remote_docker_repository.this) > 0 ? artifactory_remote_docker_repository.this[0].key : null
}
```

When I execute `terraform apply`, all the repos are created successfully. Tested with provider 7.2.0 and Artifactory 7.55.2.

Please share the full set of module files so I can reproduce this issue in my environment.

**Comment by aisvarya2** [comment]
@alexhung I'll upload the entire set of files to reproduce the bug. Also, I would like to point out that the plugin crashes occur when multiple repos i.e say **15+ repos are created at once**. As mentioned above, we have 60+ repos created directly using the resource block and it works seamlessly but when the same is modularized this way, we are facing plugin crash.

Files according to the module structure
├── artifactory-projects
│ ├── main.tf
│ ├── outputs.tf
│ └── variables.tf
└── artifactory-repos
├── main.tf
├── outputs.tf
└── variables.tf

Project creation
[main.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10979129/main.txt)
[outputs.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10979130/outputs.txt)
[variables.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10979131/variables.txt)

Repo creation
[main.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10980420/main.txt)
[outputs.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10980421/outputs.txt)
[variables.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10980422/variables.txt)

Module call
[sample_code.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10980433/sample_code.txt)

Attaching the crash log once again,
[artifactory.plugin.crash.log.txt](https://github.com/jfrog/terraform-provider-artifactory/files/10980506/artifactory.plugin.crash.log.txt)

**Comment by alexhung** [comment]
@aisvarya2 Thanks for the files. I'll investigate further.

**Comment by alexhung** [comment]
@aisvarya2 Thank you for sharing the module files. I am able to reproduce the issue.

## Cause

Like a plan crash, it is sequence of many different events/errors that leads to the final one you reported.

1. Using modules means Terraform can parallelize the execution (vs single thread with one root module). By default the parallelism is set to 10. This means with enough modules, Terraform can saturate Artifactory ability to handle the incoming API requests. This is of course dependent on many factors (CPU, memory, etc.)
2. These parallel requests in your example result in Artifactory unable to create one of the repository.
3. This failure in creating a repository results in the module output being empty string (`""`):
```hcl
output "local_docker_key" {
  value = try(artifactory_local_docker_v2_repository.this[0].key, "")
}
```
which in turn results in the `repositories` list containing an empty string.
4. Unfortunately, there's a bug in the Terraform SDKv2 framework that translate this empty string into `nil` value: https://github.com/hashicorp/terraform-plugin-sdk/issues/741 This is what the final error you see, as our provider tries to transform the `repositories` attribute value (list of repo keys) into list of strings for the Artifactory API request.

## Workarounds and Fix

We'll update the code to filter out `nil` value in the provider. This will prevent the provider from panicing.

In the meantime, you can bypass this error by compacting the repository list:

```hcl
repositories = compact([
  module.foo-pypi-dev-local.local_pypi_key,
  module.foo-pypi-dev-proxy.remote_pypi_key
])
```

But both will not prevent the root cause which is Artifactory being overwhelmed with requests. To workaround this, I recommend experimenting with decrementing the `-parallelism=n` argument with `terraform apply`.
